# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd65a38436de88e9e78b0b98fe55257f3805cfd027603f22bf3bb472a0cab3fd4b36090de2823bafe737cec24d4dcc15edf9928fd8e032fb30ae4c84077c9717

test:
  secret_key_base: ba9577a76944578f17244721e7e3d8493991ae07171b08a86e73729c088a507fb20e91c20f84161fc26b9aa6ff76693eb60d74e4170a6310b1fbfa001e5863d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
